services:
  kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    ports:
      - 127.0.0.1:3001:3001
    restart: always
    security_opt:
      # https://stackoverflow.com/a/78624998/167815 (Debian 12, May 2025)
      - apparmor=unconfined
